DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.154.220) 0.58ms
INFO:root:Websocket served at time: Sat Oct 19 11:39:28 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.220) 0.71ms
INFO:root:Websocket served at time: Sat Oct 19 11:40:02 2019
INFO:root:**********WebSocket closed**********
WARNING:tornado.access:403 GET / (202.118.99.182) 0.43ms
DEBUG:tornado.general:Cross origin websockets not allowed
INFO:tornado.access:101 GET / (219.217.154.220) 0.72ms
INFO:root:Websocket served at time: Sat Oct 19 11:41:12 2019
INFO:root:**********WebSocket closed**********
WARNING:tornado.access:403 GET / (202.118.99.182) 0.49ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.40ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.41ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.39ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.39ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.40ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.51ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.40ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.39ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.41ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.54ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.54ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.39ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.40ms
DEBUG:tornado.general:Cross origin websockets not allowed
DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.154.220) 0.58ms
INFO:root:Websocket served at time: Sat Oct 19 11:50:00 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (202.118.99.182) 0.48ms
INFO:root:Websocket served at time: Sat Oct 19 11:50:31 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.58ms
INFO:root:Websocket served at time: Sat Oct 19 11:50:51 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.154.220) 0.60ms
INFO:root:Websocket served at time: Sat Oct 19 11:56:31 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.general:Malformed HTTP message from 219.217.154.108: no colon in header line
INFO:tornado.access:101 GET / (219.217.154.108) 0.49ms
INFO:root:Websocket served at time: Sun Oct 20 10:43:00 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.81ms
INFO:root:Websocket served at time: Sun Oct 20 10:47:43 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.51ms
INFO:root:Websocket served at time: Sun Oct 20 10:48:08 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.48ms
INFO:root:Websocket served at time: Sun Oct 20 11:10:05 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.65ms
INFO:root:Websocket served at time: Sun Oct 20 11:27:48 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.48ms
INFO:root:Websocket served at time: Sun Oct 20 11:28:15 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.56ms
INFO:root:Websocket served at time: Sun Oct 20 11:29:03 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.49ms
INFO:root:Websocket served at time: Sun Oct 20 11:30:01 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.51ms
INFO:root:Websocket served at time: Sun Oct 20 11:30:57 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.50ms
INFO:root:Websocket served at time: Sun Oct 20 11:31:31 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.48ms
INFO:root:Websocket served at time: Sun Oct 20 11:32:27 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.65ms
INFO:root:Websocket served at time: Sun Oct 20 11:35:44 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.48ms
INFO:root:Websocket served at time: Sun Oct 20 11:35:58 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.55ms
INFO:root:Websocket served at time: Sun Oct 20 11:37:06 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.51ms
INFO:root:Websocket served at time: Sun Oct 20 11:37:21 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.48ms
INFO:root:Websocket served at time: Sun Oct 20 11:37:59 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.52ms
INFO:root:Websocket served at time: Sun Oct 20 11:39:55 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.51ms
INFO:root:Websocket served at time: Sun Oct 20 11:40:19 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.46ms
INFO:root:Websocket served at time: Sun Oct 20 11:41:07 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.48ms
INFO:root:Websocket served at time: Sun Oct 20 11:41:23 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.52ms
INFO:root:Websocket served at time: Sun Oct 20 11:41:45 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.46ms
INFO:root:Websocket served at time: Sun Oct 20 11:43:26 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.52ms
INFO:root:Websocket served at time: Sun Oct 20 11:44:18 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.108) 0.45ms
INFO:root:Websocket served at time: Sun Oct 20 11:44:31 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (202.118.99.182) 0.47ms
INFO:root:Websocket served at time: Sun Oct 20 15:23:08 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.48ms
INFO:root:Websocket served at time: Sun Oct 20 15:23:14 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.50ms
INFO:root:Websocket served at time: Sun Oct 20 15:36:08 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (202.118.99.182) 0.47ms
INFO:root:Websocket served at time: Sun Oct 20 15:36:13 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.52ms
INFO:root:Websocket served at time: Sun Oct 20 15:36:24 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (219.217.155.183) 0.66ms
INFO:root:Websocket served at time: Sun Oct 20 19:00:07 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.49ms
INFO:root:Websocket served at time: Sun Oct 20 19:26:51 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.54ms
INFO:root:Websocket served at time: Sun Oct 20 19:26:55 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.53ms
INFO:root:Websocket served at time: Sun Oct 20 19:29:13 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.49ms
INFO:root:Websocket served at time: Sun Oct 20 19:29:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.48ms
INFO:root:Websocket served at time: Sun Oct 20 19:30:14 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.48ms
INFO:root:Websocket served at time: Sun Oct 20 20:59:24 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.47ms
INFO:root:Websocket served at time: Sun Oct 20 21:00:05 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.45ms
INFO:root:Websocket served at time: Sun Oct 20 21:00:57 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.47ms
INFO:root:Websocket served at time: Sun Oct 20 21:01:14 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.50ms
INFO:root:Websocket served at time: Sun Oct 20 21:02:15 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.55ms
INFO:root:Websocket served at time: Sun Oct 20 21:04:37 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.50ms
INFO:root:Websocket served at time: Mon Oct 21 09:12:32 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.52ms
INFO:root:Websocket served at time: Mon Oct 21 09:14:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 09:20:00 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 09:27:27 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 09:35:10 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 09:35:42 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 09:44:34 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 09:48:05 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 09:49:36 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.53ms
INFO:root:Websocket served at time: Mon Oct 21 09:51:42 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 09:52:16 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 09:54:57 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.79ms
INFO:root:Websocket served at time: Mon Oct 21 09:55:43 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.55ms
INFO:root:Websocket served at time: Mon Oct 21 09:56:21 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.56ms
INFO:root:Websocket served at time: Mon Oct 21 09:57:12 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 09:57:48 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 10:08:00 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 10:08:10 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 10:08:44 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 10:09:51 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.52ms
INFO:root:Websocket served at time: Mon Oct 21 10:12:14 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.52ms
INFO:root:Websocket served at time: Mon Oct 21 10:13:59 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.79ms
INFO:root:Websocket served at time: Mon Oct 21 10:14:23 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.52ms
INFO:root:Websocket served at time: Mon Oct 21 10:15:44 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 10:35:05 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 10:36:08 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 10:37:17 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 10:37:39 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.53ms
INFO:root:Websocket served at time: Mon Oct 21 10:39:17 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.45ms
INFO:root:Websocket served at time: Mon Oct 21 10:44:57 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.76ms
INFO:root:Websocket served at time: Mon Oct 21 10:45:27 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 10:48:43 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 10:49:28 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.63ms
INFO:root:Websocket served at time: Mon Oct 21 10:56:58 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 11:00:01 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.69ms
INFO:root:Websocket served at time: Mon Oct 21 11:09:42 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 11:17:34 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 11:18:53 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.50ms
INFO:root:Websocket served at time: Mon Oct 21 11:20:07 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 11:20:43 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 11:21:23 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 11:21:40 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.183) 0.55ms
INFO:root:Websocket served at time: Mon Oct 21 11:23:03 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.53ms
INFO:root:Websocket served at time: Mon Oct 21 14:22:38 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.52ms
INFO:root:Websocket served at time: Mon Oct 21 14:30:56 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.65ms
INFO:root:Websocket served at time: Mon Oct 21 14:37:26 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 14:39:23 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 14:39:39 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 14:40:27 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 14:58:09 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 15:00:15 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.50ms
INFO:root:Websocket served at time: Mon Oct 21 15:02:24 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.55ms
INFO:root:Websocket served at time: Mon Oct 21 15:03:17 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 15:03:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 15:03:46 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 15:04:35 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.53ms
INFO:root:Websocket served at time: Mon Oct 21 15:05:06 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 15:10:41 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.50ms
INFO:root:Websocket served at time: Mon Oct 21 15:11:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.53ms
INFO:root:Websocket served at time: Mon Oct 21 15:11:56 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.64ms
INFO:root:Websocket served at time: Mon Oct 21 15:15:21 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 15:16:39 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.77ms
INFO:root:Websocket served at time: Mon Oct 21 15:16:52 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.54ms
INFO:root:Websocket served at time: Mon Oct 21 15:30:21 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.53ms
INFO:root:Websocket served at time: Mon Oct 21 15:31:03 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.68ms
INFO:root:Websocket served at time: Mon Oct 21 15:31:20 2019
WARNING:tornado.access:400 GET / (101.132.70.61) 0.46ms
DEBUG:tornado.general:Can "Upgrade" only to "WebSocket".
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.65ms
INFO:root:Websocket served at time: Mon Oct 21 16:16:18 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 16:16:47 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.50ms
INFO:root:Websocket served at time: Mon Oct 21 16:24:37 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 16:28:03 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 16:33:33 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 16:34:02 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 16:35:58 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 16:36:47 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.52ms
INFO:root:Websocket served at time: Mon Oct 21 16:40:47 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 16:41:24 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 16:42:05 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 16:54:13 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 16:54:26 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 19:43:41 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 19:46:10 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 19:53:32 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 19:56:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.46ms
INFO:root:Websocket served at time: Mon Oct 21 19:59:43 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.50ms
INFO:root:Websocket served at time: Mon Oct 21 20:00:38 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.50ms
INFO:root:Websocket served at time: Mon Oct 21 20:05:24 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.87ms
INFO:root:Websocket served at time: Mon Oct 21 20:05:52 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.76ms
INFO:root:Websocket served at time: Mon Oct 21 20:06:55 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 20:11:42 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.50ms
INFO:root:Websocket served at time: Mon Oct 21 20:13:20 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 20:14:41 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.57ms
INFO:root:Websocket served at time: Mon Oct 21 20:15:02 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.77ms
INFO:root:Websocket served at time: Mon Oct 21 20:15:13 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 20:16:20 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.47ms
INFO:root:Websocket served at time: Mon Oct 21 20:30:07 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 20:31:01 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.98ms
INFO:root:Websocket served at time: Mon Oct 21 20:32:33 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.45ms
INFO:root:Websocket served at time: Mon Oct 21 20:35:18 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 20:36:15 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.57ms
INFO:root:Websocket served at time: Mon Oct 21 20:37:04 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 20:38:38 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 20:39:08 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 20:40:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 20:40:59 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 20:41:07 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.52ms
INFO:root:Websocket served at time: Mon Oct 21 20:42:57 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.45ms
INFO:root:Websocket served at time: Mon Oct 21 20:44:13 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.52ms
INFO:root:Websocket served at time: Mon Oct 21 20:45:14 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.51ms
INFO:root:Websocket served at time: Mon Oct 21 20:47:54 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.49ms
INFO:root:Websocket served at time: Mon Oct 21 20:50:16 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.72ms
INFO:root:Websocket served at time: Mon Oct 21 20:50:51 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.152.37) 0.48ms
INFO:root:Websocket served at time: Mon Oct 21 20:52:37 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (202.118.99.182) 0.60ms
INFO:root:Websocket served at time: Wed Oct 23 10:11:41 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.51ms
INFO:root:Websocket served at time: Wed Oct 23 11:06:26 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.51ms
INFO:root:Websocket served at time: Wed Oct 23 11:10:15 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.49ms
INFO:root:Websocket served at time: Wed Oct 23 11:10:21 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.45ms
INFO:root:Websocket served at time: Wed Oct 23 11:10:46 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.58ms
INFO:root:Websocket served at time: Wed Oct 23 11:12:23 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.46ms
INFO:root:Websocket served at time: Wed Oct 23 11:12:28 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.50ms
INFO:root:Websocket served at time: Wed Oct 23 11:23:27 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.45ms
INFO:root:Websocket served at time: Wed Oct 23 11:24:43 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.47ms
INFO:root:Websocket served at time: Wed Oct 23 14:18:15 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.50ms
INFO:root:Websocket served at time: Wed Oct 23 14:19:14 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.91) 0.55ms
INFO:root:Websocket served at time: Thu Oct 24 10:33:32 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.91) 0.49ms
INFO:root:Websocket served at time: Thu Oct 24 10:35:59 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (42.249.26.99) 0.51ms
INFO:root:Websocket served at time: Thu Oct 24 11:03:49 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (42.249.22.65) 0.57ms
INFO:root:Websocket served at time: Thu Oct 24 15:49:25 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (42.249.22.65) 0.50ms
INFO:root:Websocket served at time: Thu Oct 24 16:05:37 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
WARNING:tornado.access:400 GET / (47.98.104.44) 0.48ms
DEBUG:tornado.general:Can "Upgrade" only to "WebSocket".
INFO:tornado.access:101 GET / (202.118.99.182) 0.47ms
INFO:root:Websocket served at time: Thu Oct 24 18:18:59 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.48ms
INFO:root:Websocket served at time: Thu Oct 24 18:19:43 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.62ms
INFO:root:Websocket served at time: Thu Oct 24 18:20:31 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.60ms
INFO:root:Websocket served at time: Thu Oct 24 18:20:37 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (223.104.176.158) 0.49ms
INFO:root:Websocket served at time: Thu Oct 24 21:52:01 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.98) 0.47ms
INFO:root:Websocket served at time: Fri Oct 25 14:06:19 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.98) 0.78ms
INFO:root:Websocket served at time: Fri Oct 25 14:13:01 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (117.136.5.98) 0.75ms
INFO:root:Websocket served at time: Fri Oct 25 14:13:01 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (117.136.5.98) 0.51ms
INFO:root:Websocket served at time: Fri Oct 25 14:13:24 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.98) 0.45ms
INFO:root:Websocket served at time: Fri Oct 25 14:14:08 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.98) 0.53ms
INFO:root:Websocket served at time: Fri Oct 25 14:15:33 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.98) 0.48ms
INFO:root:Websocket served at time: Fri Oct 25 14:27:40 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.98) 0.52ms
INFO:root:Websocket served at time: Fri Oct 25 14:40:35 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.98) 0.49ms
INFO:root:Websocket served at time: Fri Oct 25 14:53:50 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (219.217.155.102) 0.46ms
INFO:root:Websocket served at time: Fri Oct 25 14:55:00 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.102) 0.60ms
INFO:root:Websocket served at time: Fri Oct 25 14:55:01 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.102) 0.45ms
INFO:root:Websocket served at time: Fri Oct 25 14:55:01 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.98) 1.38ms
INFO:root:Websocket served at time: Fri Oct 25 14:56:01 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (117.136.5.98) 1.46ms
INFO:root:Websocket served at time: Fri Oct 25 14:56:01 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (117.136.5.98) 0.46ms
INFO:root:Websocket served at time: Fri Oct 25 14:56:14 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.53ms
INFO:root:Websocket served at time: Fri Oct 25 15:59:23 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.51ms
INFO:root:Websocket served at time: Fri Oct 25 16:00:48 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.49ms
INFO:root:Websocket served at time: Fri Oct 25 16:01:03 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.47ms
INFO:root:Websocket served at time: Fri Oct 25 16:01:26 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (42.249.23.60) 0.73ms
INFO:root:Websocket served at time: Fri Oct 25 16:47:14 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.general:Malformed HTTP message from 58.213.153.13: Malformed HTTP request line
WARNING:tornado.access:400 GET / (58.213.153.13) 0.48ms
DEBUG:tornado.general:Can "Upgrade" only to "WebSocket".
WARNING:tornado.access:400 GET / (58.213.153.13) 0.50ms
DEBUG:tornado.general:Can "Upgrade" only to "WebSocket".
WARNING:tornado.access:404 POST /sdk (58.213.153.13) 0.44ms
WARNING:tornado.access:404 GET /nmaplowercheck1572029045 (58.213.153.13) 0.29ms
WARNING:tornado.access:400 GET / (58.213.153.13) 0.37ms
DEBUG:tornado.general:Can "Upgrade" only to "WebSocket".
WARNING:tornado.access:404 GET /evox/about (58.213.153.13) 0.39ms
WARNING:tornado.access:404 GET /HNAP1 (58.213.153.13) 0.41ms
WARNING:tornado.access:400 GET / (58.213.153.13) 0.47ms
DEBUG:tornado.general:Can "Upgrade" only to "WebSocket".
WARNING:tornado.access:400 GET / (58.213.153.13) 0.60ms
DEBUG:tornado.general:Can "Upgrade" only to "WebSocket".
WARNING:tornado.access:400 GET / (58.213.153.13) 0.45ms
DEBUG:tornado.general:Can "Upgrade" only to "WebSocket".
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sat Oct 26 10:09:27 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.46ms
INFO:root:Websocket served at time: Sat Oct 26 10:30:44 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.59ms
INFO:root:Websocket served at time: Sat Oct 26 10:31:23 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.51ms
INFO:root:Websocket served at time: Sat Oct 26 10:37:35 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sat Oct 26 10:38:20 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sat Oct 26 10:40:39 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sat Oct 26 10:41:15 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.69ms
INFO:root:Websocket served at time: Sat Oct 26 10:43:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sat Oct 26 10:46:24 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sat Oct 26 10:47:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.53ms
INFO:root:Websocket served at time: Sat Oct 26 10:47:47 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sat Oct 26 10:50:44 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.51ms
INFO:root:Websocket served at time: Sat Oct 26 10:52:33 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sat Oct 26 10:52:52 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.46ms
INFO:root:Websocket served at time: Sat Oct 26 10:54:49 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sat Oct 26 10:55:07 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.46ms
INFO:root:Websocket served at time: Sat Oct 26 10:57:42 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.45ms
INFO:root:Websocket served at time: Sat Oct 26 10:58:26 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sat Oct 26 11:00:44 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.56ms
INFO:root:Websocket served at time: Sat Oct 26 11:00:59 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sat Oct 26 11:01:38 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.54ms
INFO:root:Websocket served at time: Sat Oct 26 11:02:44 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sat Oct 26 11:34:33 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sat Oct 26 11:34:55 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sat Oct 26 11:35:52 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (202.118.99.182) 0.78ms
INFO:root:Websocket served at time: Sat Oct 26 14:42:58 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.47ms
INFO:root:Websocket served at time: Sat Oct 26 14:43:07 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.65ms
INFO:root:Websocket served at time: Sat Oct 26 14:57:15 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.49ms
INFO:root:Websocket served at time: Sat Oct 26 14:57:24 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (219.217.155.15) 0.51ms
INFO:root:Websocket served at time: Sat Oct 26 21:24:43 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sat Oct 26 21:28:31 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sat Oct 26 21:31:37 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.45ms
INFO:root:Websocket served at time: Sat Oct 26 21:32:34 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.46ms
INFO:root:Websocket served at time: Sat Oct 26 21:35:11 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.69ms
INFO:root:Websocket served at time: Sat Oct 26 21:36:52 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sat Oct 26 21:37:53 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.75ms
INFO:root:Websocket served at time: Sat Oct 26 21:41:49 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.53ms
INFO:root:Websocket served at time: Sat Oct 26 21:42:15 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 10:07:58 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.56ms
INFO:root:Websocket served at time: Sun Oct 27 10:09:50 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.46ms
INFO:root:Websocket served at time: Sun Oct 27 10:13:54 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.53ms
INFO:root:Websocket served at time: Sun Oct 27 10:17:22 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 10:18:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 10:19:14 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.55ms
INFO:root:Websocket served at time: Sun Oct 27 10:19:30 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.62ms
INFO:root:Websocket served at time: Sun Oct 27 10:20:50 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 10:22:18 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 10:23:33 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.56ms
INFO:root:Websocket served at time: Sun Oct 27 10:25:43 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 10:28:24 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.56ms
INFO:root:Websocket served at time: Sun Oct 27 10:29:35 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sun Oct 27 10:30:01 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.55ms
INFO:root:Websocket served at time: Sun Oct 27 10:30:32 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.57ms
INFO:root:Websocket served at time: Sun Oct 27 10:33:15 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sun Oct 27 10:40:35 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.55ms
INFO:root:Websocket served at time: Sun Oct 27 10:42:13 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 10:46:34 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.57ms
INFO:root:Websocket served at time: Sun Oct 27 10:46:55 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.59ms
INFO:root:Websocket served at time: Sun Oct 27 10:47:46 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.54ms
INFO:root:Websocket served at time: Sun Oct 27 10:48:01 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 10:48:07 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.70ms
INFO:root:Websocket served at time: Sun Oct 27 10:48:14 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.51ms
INFO:root:Websocket served at time: Sun Oct 27 10:48:47 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.60ms
INFO:root:Websocket served at time: Sun Oct 27 10:50:23 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.51ms
INFO:root:Websocket served at time: Sun Oct 27 10:51:18 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 10:53:51 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.55ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:20 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.45ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:21 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.53ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:23 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:25 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:27 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.64ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:29 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:31 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:33 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:46 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 10:56:48 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 10:57:24 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.54ms
INFO:root:Websocket served at time: Sun Oct 27 10:57:26 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 10:57:28 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.51ms
INFO:root:Websocket served at time: Sun Oct 27 10:57:30 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.53ms
INFO:root:Websocket served at time: Sun Oct 27 10:57:32 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.46ms
INFO:root:Websocket served at time: Sun Oct 27 10:57:34 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 10:57:36 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.53ms
INFO:root:Websocket served at time: Sun Oct 27 10:58:59 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.77ms
INFO:root:Websocket served at time: Sun Oct 27 10:59:31 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:00:02 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sun Oct 27 11:00:18 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.56ms
INFO:root:Websocket served at time: Sun Oct 27 11:02:36 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.55ms
INFO:root:Websocket served at time: Sun Oct 27 11:03:37 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 11:04:09 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:04:24 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.46ms
INFO:root:Websocket served at time: Sun Oct 27 11:05:48 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.45ms
INFO:root:Websocket served at time: Sun Oct 27 11:05:49 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.51ms
INFO:root:Websocket served at time: Sun Oct 27 11:05:51 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.46ms
INFO:root:Websocket served at time: Sun Oct 27 11:05:53 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.56ms
INFO:root:Websocket served at time: Sun Oct 27 11:05:54 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 11:05:56 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 11:05:58 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 11:05:59 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.61ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:01 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.64ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:03 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.63ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:04 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.45ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:06 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:07 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.62ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:09 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:11 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:12 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.77ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:14 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:16 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:17 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.82ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:19 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:21 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:23 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.46ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:24 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.45ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:26 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:28 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.57ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:33 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 11:06:40 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.64ms
INFO:root:Websocket served at time: Sun Oct 27 11:07:13 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.54ms
INFO:root:Websocket served at time: Sun Oct 27 11:07:15 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:07:17 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:07:19 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sun Oct 27 11:07:21 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.68ms
INFO:root:Websocket served at time: Sun Oct 27 11:07:23 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 11:12:30 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:12:32 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 11:12:34 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:12:36 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 11:12:38 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.53ms
INFO:root:Websocket served at time: Sun Oct 27 11:12:40 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sun Oct 27 11:12:42 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.73ms
INFO:root:Websocket served at time: Sun Oct 27 11:15:03 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.54ms
INFO:root:Websocket served at time: Sun Oct 27 11:16:09 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.52ms
INFO:root:Websocket served at time: Sun Oct 27 11:16:12 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.57ms
INFO:root:Websocket served at time: Sun Oct 27 11:16:14 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.57ms
INFO:root:Websocket served at time: Sun Oct 27 11:16:17 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.50ms
INFO:root:Websocket served at time: Sun Oct 27 11:16:19 2019
ERROR:tornado.application:Uncaught exception GET / (219.217.155.15)
HTTPServerRequest(protocol='http', host='39.100.5.176:30104', method='GET', uri='/', version='HTTP/1.1', remote_ip='219.217.155.15')
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 649, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/Chunar/codes/Monitor_pi/motor_factory/overview/overview_web_server.py", line 27, in on_message
    data_dict = json.loads(data)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.51ms
INFO:root:Websocket served at time: Sun Oct 27 11:16:54 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.49ms
INFO:root:Websocket served at time: Sun Oct 27 11:18:41 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.69ms
INFO:root:Websocket served at time: Sun Oct 27 11:20:24 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.51ms
INFO:root:Websocket served at time: Sun Oct 27 11:21:29 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.65ms
INFO:root:Websocket served at time: Sun Oct 27 11:22:31 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.48ms
INFO:root:Websocket served at time: Sun Oct 27 11:23:16 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (219.217.155.15) 0.58ms
INFO:root:Websocket served at time: Sun Oct 27 11:24:50 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.56ms
INFO:root:Websocket served at time: Sun Oct 27 11:30:45 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.75ms
INFO:root:Websocket served at time: Sun Oct 27 11:48:00 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.67ms
INFO:root:Websocket served at time: Sun Oct 27 15:18:17 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.73ms
INFO:root:Websocket served at time: Sun Oct 27 15:18:33 2019
INFO:root:**********WebSocket closed**********
DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.155.15) 0.75ms
INFO:root:Websocket served at time: Sun Oct 27 15:30:17 2019
INFO:root:**********WebSocket closed**********
DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.155.15) 0.63ms
INFO:root:Websocket served at time: Sun Oct 27 15:31:39 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.155.15) 0.47ms
INFO:root:Websocket served at time: Sun Oct 27 15:32:04 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (219.217.155.15) 0.53ms
INFO:root:Websocket served at time: Sun Oct 27 15:33:54 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.155.15) 0.63ms
INFO:root:Websocket served at time: Sun Oct 27 15:39:52 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.155.15) 0.63ms
INFO:root:Websocket served at time: Sun Oct 27 16:00:20 2019
DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.155.15) 0.62ms
INFO:root:Websocket served at time: Sun Oct 27 16:04:22 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
