DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.154.220) 0.58ms
INFO:root:Websocket served at time: Sat Oct 19 11:39:28 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (219.217.154.220) 0.71ms
INFO:root:Websocket served at time: Sat Oct 19 11:40:02 2019
INFO:root:**********WebSocket closed**********
WARNING:tornado.access:403 GET / (202.118.99.182) 0.43ms
DEBUG:tornado.general:Cross origin websockets not allowed
INFO:tornado.access:101 GET / (219.217.154.220) 0.72ms
INFO:root:Websocket served at time: Sat Oct 19 11:41:12 2019
INFO:root:**********WebSocket closed**********
WARNING:tornado.access:403 GET / (202.118.99.182) 0.49ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.40ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.41ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.39ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.39ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.40ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.51ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.40ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.39ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.41ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.54ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.42ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.54ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.39ms
DEBUG:tornado.general:Cross origin websockets not allowed
WARNING:tornado.access:403 GET / (202.118.99.182) 0.40ms
DEBUG:tornado.general:Cross origin websockets not allowed
DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.154.220) 0.58ms
INFO:root:Websocket served at time: Sat Oct 19 11:50:00 2019
INFO:root:**********WebSocket closed**********
INFO:tornado.access:101 GET / (202.118.99.182) 0.48ms
INFO:root:Websocket served at time: Sat Oct 19 11:50:31 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
INFO:tornado.access:101 GET / (202.118.99.182) 0.58ms
INFO:root:Websocket served at time: Sat Oct 19 11:50:51 2019
INFO:root:**********WebSocket closed**********
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
DEBUG:asyncio:Using selector: EpollSelector
INFO:tornado.access:101 GET / (219.217.154.220) 0.60ms
INFO:root:Websocket served at time: Sat Oct 19 11:56:31 2019
INFO:root:**********WebSocket closed**********
